### ISSUE TITLE
Issues with docker-compose

### ISSUE THREAD

**Issue by SachinMaharana** [ichux/the-artofpostgresql#5]
Hi. Thanks for making this. i have the book but having difficulty in setting it up. I came across your repo and it failing here. Any idea why?

artofpostgres is up-to-date
docker-compose run --rm database psql "postgresql://postgres@database:5432" -c 'CREATE DATABASE appdev;'
psql: error: could not connect to server: could not translate host name "database" to address: No address associated with hostname
Makefile:51: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 2

**Comment by ichux** [comment]
Hi @SachinMaharana 

I do not know why it is failing but I can volunteer to do peer review with you if that is fine by. Do let me know. My timezone is GMT + 1. 

We could do Skype or Zoom while I help you fix it. Everything worked fine at my end and I verified it before pushing to github.

**Comment by ichux** [comment]
@SachinMaharana 
I have fixed the issue, it was due to **POSTGRES_HOST_AUTH_METHOD** that was missing in the  **docker-compose** file.

It was added sometime ago and I needed to update the file and everything is fine now. In case of next time, type `make logs` to help you debug what might be causing the issue.

Cheers
